name: Ryan Endacott
description: Builder, founder, tinkerer.
meta_description: Ryan Endacott — builder, founder, tinkerer.

markdown: kramdown
highlighter: rouge
logo: '/images/og-default-gemini.png'
paginate: 3
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate

author:
  name: 'Ryan Endacott'
  website: 'http://ryan.endacott.me'
  bio: ''
  image: '/images/me3.jpg'

# Details for the RSS feed generator
url: 'https://ryan.endacott.me'

# Social Media
social:
  twitter: RyanEndacott
  github: ryan-endacott
  linkedin: ryanendacott
