name: Ryan Endacott
description: Software Engineer and Entrepreneur
meta_description: Ryan Endacott's personal website - Software Engineer and Entrepreneur

markdown: kramdown
highlighter: rouge
logo: '/images/me3.jpg'
paginate: 3
excerpt_separator: <!--more-->

plugins:
  - jekyll-paginate

author:
  name: 'Ryan Endacott'
  website: 'http://ryan.endacott.me'
  bio: ''
  image: '/images/me3.jpg'

# Details for the RSS feed generator
url: 'http://ryan.endacott.me'

# Social Media
social:
  twitter: RyanEndacott
  github: ryan-endacott
  linkedin: ryanendacott
