name: Ryan Endacott
description:
meta_description:

markdown: redcarpet
highlighter: pygments
logo: '/images/me2.jpg'
paginate: 3

author:
  name: 'Ryan Endacott'
  website: 'http://ryan.endacott.me'
  bio: ''
  image: '/images/me2.jpg'

# Details for the RSS feed generator
url: 'http://ryan.endacott.me'
